services:
  - type: web
    name: save-note-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python save_note.py
    envVars:
      - key: DROPBOX_APP_KEY
        fromEnvVar: DROPBOX_APP_KEY
      - key: DROPBOX_APP_SECRET
        fromEnvVar: DROPBOX_APP_SECRET
      - key: DROPBOX_REFRESH_TOKEN
        fromEnvVar: DROPBOX_REFRESH_TOKEN
