name: Trigger Staging Tests
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  trigger-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger staging deployment and tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type":"staging_test","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'